/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import  * as THREE from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/magic.glb')
  return (

    <group {...props} scale={4} dispose={null}
      rotation={[Math.PI / 2, 0, 0]} >
       {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.path44.geometry}
           material={new THREE.MeshStandardMaterial({ color: 'purple' })} // slate grey

        position={[0, 0, -0.6]}
        scale={[46.727, 1, 46.727]}
      />   */}
      <mesh 
        castShadow
        receiveShadow
        geometry={nodes.path44001.geometry}
        material={new THREE.MeshStandardMaterial({ color: '#0b0b0b' })} // slate grey
        position={[0, 0, 0]}
        scale={[5, 0.1, 5]}
      />
    
    </group>
  )
}

useGLTF.preload('/magic.glb')