/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import  * as THREE from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('magic.glb')
  return (

    <group {...props} scale={1} dispose={null}
      rotation={[Math.PI / 2, 0, 0]} >
       {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.path44.geometry}
           material={new THREE.MeshStandardMaterial({ color: 'purple' })} // slate grey

       
        scale={[46.727, 1, 46.727]}
      />   */}
      <mesh 
        castShadow
        receiveShadow
        geometry={nodes.path44001.geometry}
        material={new THREE.MeshStandardMaterial({ color: '#363636' })} // slate grey

        scale={[10, 0.2, 10]}
      />
    
    </group>
  )
}

useGLTF.preload('magic.glb')