/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/magic.glb')
  return (

    <group {...props} scale={1} dispose={null}
      rotation={[Math.PI / 2, 0, 0]} >
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.path44.geometry}
        material={materials.Material}
        position={[0, 3.554, 1.903]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[46.727, 1, 46.727]}
      /> */}
      <mesh 
        castShadow
        receiveShadow
        geometry={nodes.path44001.geometry}
        material={materials['SVGMat.009']}
        position={[0, 0, 0]}
        scale={[46.727, 1, 46.727]}
      />
    
    </group>
  )
}

useGLTF.preload('/magic.glb')